package com.example.demo.entity;


import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class Task {

    //@Id: Marks the annotated field as the primary key for the entity, ensuring each record is unique
    //@GeneratedValue: Indicates that the primary key value will be automatically generated by the persistence provider
    //strategy = GenerationType.IDENTITY: specifies HOW the ID is generated, by telling the database to use its built-in
    //identity column feature (auto-increment) to assign the next available number for that column
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String title;
    private String description;
    private boolean completed;

    public Task(){}

    public Task(String title, String description){
        this.title = title;
        this.description = description;
        this.completed = false;
    }

    public String getTitle(){
        return title;
    }

    public void setTitle(String title){
        this.title = title;
    }

    public Long getId(){
        return id;
    }

    public void setId(Long Id){
        this.id = Id;
    }

    public String getDescription(){
        return description;
    }

    public void setDescription(String description){
        this.description = description;
    }

    public boolean getCompleted(){
        return completed;
    }

    public void setCompleted(boolean completed){
        this.completed = completed;
    }
}
